# Two state Markov chains

In [1]:
import numpy as np

**1.17. Market research suggests that in a five year period 8% of people with cable television will get rid of it, and 26% of those without it will sign up for it. Compare the predictions of the Markov chain model with the following data on the fraction of people with cable TV: 56.4% in 1990, 63.4% in 1995, and 68.0% in 2000. What is the long run fraction of people with cable TV?**

In [2]:
tv = np.array([
    [.92, .08],
    [.26, .74],
])
init_state = np.array([.564, 1 - .564])
print(f"Markov chain model for 1995s: {np.round(np.dot(init_state, tv)[0], 4) * 100}%")
print(f"Markov chain model for 2000s: {np.round(np.dot(init_state, np.linalg.matrix_power(tv, 2))[0], 4) * 100}%")

Markov chain model for 1995s: 63.22%
Markov chain model for 2000s: 67.73%


**1.18. A sociology professor postulates that in each decade 8% of women in the work force leave it and 20% of the women not in it begin to work. Compare the predictions of his model with the following data on the percentage of women working: 43.3% in 1970, 51.5% in 1980, 57.5% in 1990, and 59.8% in 2000. In the long run what fraction of women will be working?**

In [3]:
woman_workforce = np.array([
    [.92, .08],
    [.2, .8]
])
init_state = np.array([.43, 1 - .43])
print(
    f"Markov chain model for 1980s: "
    f"{np.round(np.dot(init_state, woman_workforce)[0] * 100, 2)}%"
)
print(
    f"Markov chain model for 1990s: "
    f"{np.round(np.dot(init_state, np.linalg.matrix_power(woman_workforce, 2))[0] * 100, 2)}%"
)
print(
    f"Markov chain model for 2000s: "
    f"{np.round(np.dot(init_state, np.linalg.matrix_power(woman_workforce, 3))[0] * 100, 2)}%"
)

pi = np.array([.2, .08]) / (.2 + .08)
print(f"In long run it will be: {np.round(pi[0] * 100, 1)}%")

Markov chain model for 1980s: 50.96%
Markov chain model for 1990s: 56.69%
Markov chain model for 2000s: 60.82%
In long run it will be: 71.4%


**1.19. A rapid transit system has just started operating. In the first month of operation, it was found that 25% of commuters are using the system while 75% are traveling by automobile. Suppose that each month 10% of transit users go back to using their cars, while 30% of automobile users switch to the transit system. (a) Compute the three step transition probability $p^3$. (b) What will be the fractions using rapid transit in the fourth month? (c) In the long run?**

In [4]:
transit_system = np.array([
    [.9, .1], 
    [.3, .7]
])
init_state = np.array([.25, .75])
pi = np.array([.3, .1]) / (.3 + .1)
print(f"(a) p^3: \n{np.linalg.matrix_power(transit_system, 3)}\n")
print(
    f"(b) Fractions using rapid transit in the fourth month: "
    f"{np.round(np.dot(init_state, np.linalg.matrix_power(transit_system, 3))[0] * 100, 2)}%\n"
)
print(f"(c) In long run: {np.round(pi[0] * 100, 2)}%")

(a) p^3: 
[[0.804 0.196]
 [0.588 0.412]]

(b) Fractions using rapid transit in the fourth month: 64.2%

(c) In long run: 75.0%


**1.20. A regional health study indicates that from one year to the next, 75% percent of smokers will continue to smoke while 25% will quit. 8% of those who stopped smoking will resume smoking while 92% will not. If 70% of the population were smokers in 1995, what fraction will be smokers in 1998? in 2005? in the long run?**

In [5]:
smokers = np.array([
    [.75, .25],
    [.08, .92]
])
init_state = np.array([.7, .3])
pi = np.array([.08, .25]) / (.25 + .08)

print(
    f"Smokers in 1998: "
    f"{np.round(np.dot(init_state, np.linalg.matrix_power(smokers, 3))[0] * 100, 2)}%"
)
print(
    f"Smokers in 2005: "
    f"{np.round(np.dot(init_state, np.linalg.matrix_power(smokers, 10))[0] * 100, 2)}%"
)
print(f"Smokers in long run: {np.round(pi[0] * 100, 2)}%")

Smokers in 1998: 38.0%
Smokers in 2005: 25.08%
Smokers in long run: 24.24%


**1.21. Three of every four trucks on the road are followed by a car, while only one of every five cars is followed by a truck. What fraction of vehicles on the road are trucks?**

In [6]:
trucks = np.array([
    [1/4, 3/4],
    [4/5, 1/5]
])
print(f"Fraction of trucks: {np.round((1/5) / (1/5 + 3/4), 2)}")

Fraction of trucks: 0.21


**1.22. In a test paper the questions are arranged so that 3/4’s of the time a True answer is followed by a True, while 2/3’s of the time a False answer is followed by a False. You are confronted with a 100 question test paper. Approximately what fraction of the answers will be True.**

In [7]:
print(f"Fraction of True's {np.round((1/3)/(1/4 + 1/3), 2)}")

Fraction of True's 0.57


**1.23. In unprofitable times corporations sometimes suspend dividend payments. Suppose that after a dividend has been paid the next one will be paid with probability 0.9, while after a dividend is suspended the next one will be suspended with probability 0.6. In the long run what is the fraction of dividends that will be paid?**

In [8]:
print(f"Long term fraction of dividends: {np.round((.4)/(.4+.1), 2)}")

Long term fraction of dividends: 0.8


**1.24. Census results reveal that in the United States 80% of the daughters of working women work and that 30% of the daughters of nonworking women work. (a) Write the transition probability for this model. (b) In the long run what fraction of women will be working?**

In [9]:
daughters = np.array([
    [.8, .2],
    [.3, .7]
])
print(f"(a) transition probability: \n {daughters}\n")
print(f"(b) in long term {np.round((.3) / (.5), 2)}")

(a) transition probability: 
 [[0.8 0.2]
 [0.3 0.7]]

(b) in long term 0.6


**1.25. When a basketball player makes a shot then he tries a harder shot the next time and hits (H) with probability 0.4, misses (M) with probability 0.6. When he misses he is more conservative the next time and hits (H) with proba bility 0.7, misses (M) with probability 0.3. (a) Write the transition probability for the two state Markov chain with state space {H,M}. (b) Find the long-run fraction of time he hits a shot.**

In [10]:
basketball = np.array([
    [.4, .6], 
    [.7, .3]
])
print(f"(a) transition probability: \n {basketball}\n")
print(f"(b) in long term {np.round((.7) / (.6 + .7), 2)}")

(a) transition probability: 
 [[0.4 0.6]
 [0.7 0.3]]

(b) in long term 0.54


**1.26. Folk wisdom holds that in Ithaca in the summer it rains 1/3 of the time, but a rainy day is followed by a second one with probability 1/2. Suppose that Ithaca weather is a Markov chain. What is its transition probability?**

We know that $p(r, r)=p(r,s) = \frac{1}{2}$, from detailed balanced condition $\frac{1}{3}p(r,s)=\frac{2}{3}p(s,r)$ which implies $\frac{1}{4}=p(s,r)$

In [11]:
ithaca = np.array([
    [3/4, 1/4],
    [1/2, 1/2]
])
print(f"Transition probability: \n {ithaca}\n")

Transition probability: 
 [[0.75 0.25]
 [0.5  0.5 ]]

